spring:
  datasource:
    url: jdbc:postgresql://trb-users-db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    locations: migrations
random-error:
  is-enable: true
  probability-average: 0.5
  probability-extreme: 0.9
  extreme-period-duration-min: 1
  extreme-period-frequency-min: 2